//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close settings.
        /// </summary>
        public static string btnCloseSettings {
            get {
                return ResourceManager.GetString("btnCloseSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string btnDetails {
            get {
                return ResourceManager.GetString("btnDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string btnNo {
            get {
                return ResourceManager.GetString("btnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings.
        /// </summary>
        public static string btnSaveSettings {
            get {
                return ResourceManager.GetString("btnSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change settings.
        /// </summary>
        public static string btnSettings {
            get {
                return ResourceManager.GetString("btnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string btnYes {
            get {
                return ResourceManager.GetString("btnYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose championship.
        /// </summary>
        public static string gbChampionShip {
            get {
                return ResourceManager.GetString("gbChampionShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose language.
        /// </summary>
        public static string gbLanguage {
            get {
                return ResourceManager.GetString("gbLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window size.
        /// </summary>
        public static string gbWindowSize {
            get {
                return ResourceManager.GetString("gbWindowSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to save data?.
        /// </summary>
        public static string lbAreYouSure {
            get {
                return ResourceManager.GetString("lbAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?.
        /// </summary>
        public static string lbAreYouSureExit {
            get {
                return ResourceManager.GetString("lbAreYouSureExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away Team.
        /// </summary>
        public static string lbAwayTeam {
            get {
                return ResourceManager.GetString("lbAwayTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain:.
        /// </summary>
        public static string lbCaptain {
            get {
                return ResourceManager.GetString("lbCaptain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change settings.
        /// </summary>
        public static string lbChangeSettings {
            get {
                return ResourceManager.GetString("lbChangeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals:.
        /// </summary>
        public static string lbGoals {
            get {
                return ResourceManager.GetString("lbGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals conceded:.
        /// </summary>
        public static string lbGoalsConceded {
            get {
                return ResourceManager.GetString("lbGoalsConceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals difference:.
        /// </summary>
        public static string lbGoalsDiff {
            get {
                return ResourceManager.GetString("lbGoalsDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals scored:.
        /// </summary>
        public static string lbGoalsScored {
            get {
                return ResourceManager.GetString("lbGoalsScored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Team.
        /// </summary>
        public static string lbHomeTeam {
            get {
                return ResourceManager.GetString("lbHomeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loses:.
        /// </summary>
        public static string lbLoses {
            get {
                return ResourceManager.GetString("lbLoses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose settings.
        /// </summary>
        public static string lbSettings {
            get {
                return ResourceManager.GetString("lbSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total matches:.
        /// </summary>
        public static string lbTotalMatches {
            get {
                return ResourceManager.GetString("lbTotalMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undecided:.
        /// </summary>
        public static string lbUndecided {
            get {
                return ResourceManager.GetString("lbUndecided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wins:.
        /// </summary>
        public static string lbWins {
            get {
                return ResourceManager.GetString("lbWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow Cards:.
        /// </summary>
        public static string lbYellowCards {
            get {
                return ResourceManager.GetString("lbYellowCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        public static string rbCro {
            get {
                return ResourceManager.GetString("rbCro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string rbEng {
            get {
                return ResourceManager.GetString("rbEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string rbFemale {
            get {
                return ResourceManager.GetString("rbFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string rbMale {
            get {
                return ResourceManager.GetString("rbMale", resourceCulture);
            }
        }
    }
}
