//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add selected favourite player.
        /// </summary>
        internal static string btnAddFavouritePlayer {
            get {
                return ResourceManager.GetString("btnAddFavouritePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add player image.
        /// </summary>
        internal static string btnAddPlayerImage {
            get {
                return ResourceManager.GetString("btnAddPlayerImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string btnConfirm {
            get {
                return ResourceManager.GetString("btnConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string btnExit {
            get {
                return ResourceManager.GetString("btnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string btnNo {
            get {
                return ResourceManager.GetString("btnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string btnPrint {
            get {
                return ResourceManager.GetString("btnPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected favourite player.
        /// </summary>
        internal static string btnRemovePlayer {
            get {
                return ResourceManager.GetString("btnRemovePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        internal static string btnSaveChanges {
            get {
                return ResourceManager.GetString("btnSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings.
        /// </summary>
        internal static string btnSaveSettings {
            get {
                return ResourceManager.GetString("btnSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string btnSettings {
            get {
                return ResourceManager.GetString("btnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string btnYes {
            get {
                return ResourceManager.GetString("btnYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmSettings.
        /// </summary>
        internal static string ConfirmSettingsForm {
            get {
                return ResourceManager.GetString("ConfirmSettingsForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Championship.
        /// </summary>
        internal static string gbChampionship {
            get {
                return ResourceManager.GetString("gbChampionship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string gbLanguage {
            get {
                return ResourceManager.GetString("gbLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All players.
        /// </summary>
        internal static string lbAllPlayers {
            get {
                return ResourceManager.GetString("lbAllPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to save settings?.
        /// </summary>
        internal static string lbAreYouSure {
            get {
                return ResourceManager.GetString("lbAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain:.
        /// </summary>
        internal static string lbCaptain {
            get {
                return ResourceManager.GetString("lbCaptain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your country.
        /// </summary>
        internal static string lbChooseCountry {
            get {
                return ResourceManager.GetString("lbChooseCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose settings.
        /// </summary>
        internal static string lbChooseSettings {
            get {
                return ResourceManager.GetString("lbChooseSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t choose country!.
        /// </summary>
        internal static string lbError {
            get {
                return ResourceManager.GetString("lbError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returning to start point of this application..
        /// </summary>
        internal static string lbError2 {
            get {
                return ResourceManager.GetString("lbError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite players.
        /// </summary>
        internal static string lbFavouritePlayers {
            get {
                return ResourceManager.GetString("lbFavouritePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals:.
        /// </summary>
        internal static string lbGoals {
            get {
                return ResourceManager.GetString("lbGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string lbIsCaptainFalse {
            get {
                return ResourceManager.GetString("lbIsCaptainFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string lbIsCaptainTrue {
            get {
                return ResourceManager.GetString("lbIsCaptainTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only have up to 3 favourite players.
        /// </summary>
        internal static string lblErrorNumberSelectedPlayer {
            get {
                return ResourceManager.GetString("lblErrorNumberSelectedPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most goals.
        /// </summary>
        internal static string lbMostGoals {
            get {
                return ResourceManager.GetString("lbMostGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Menu.
        /// </summary>
        internal static string lbPlayerMenu {
            get {
                return ResourceManager.GetString("lbPlayerMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular Matches.
        /// </summary>
        internal static string lbPopularMatches {
            get {
                return ResourceManager.GetString("lbPopularMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank List Menu.
        /// </summary>
        internal static string lbRankListMenu {
            get {
                return ResourceManager.GetString("lbRankListMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string lbSettings {
            get {
                return ResourceManager.GetString("lbSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitors:.
        /// </summary>
        internal static string lbVisitors {
            get {
                return ResourceManager.GetString("lbVisitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow cards:.
        /// </summary>
        internal static string lbYellowCard {
            get {
                return ResourceManager.GetString("lbYellowCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most yellow cards.
        /// </summary>
        internal static string lbYellowCards {
            get {
                return ResourceManager.GetString("lbYellowCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RankList.
        /// </summary>
        internal static string RankListForm {
            get {
                return ResourceManager.GetString("RankListForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string rbEng {
            get {
                return ResourceManager.GetString("rbEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string rbFemale {
            get {
                return ResourceManager.GetString("rbFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        internal static string rbHrv {
            get {
                return ResourceManager.GetString("rbHrv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string rbMale {
            get {
                return ResourceManager.GetString("rbMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsForm {
            get {
                return ResourceManager.GetString("SettingsForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string StartForm {
            get {
                return ResourceManager.GetString("StartForm", resourceCulture);
            }
        }
    }
}
